name: Cypress Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Start your React app (adjust if using npm run dev)
      - name: Start app
        run: npm start &
      
      # 5️⃣ Wait until app is ready
      - name: Wait for app
        run: npx wait-on http://localhost:5173

      # 6️⃣ Run Cypress tests
      - name: Run Cypress
        run: npx cypress run

      # 7️⃣ Upload artifacts if tests fail (optional)
      - name: Upload Cypress Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots